({
	doSomethingThatFails : function() {
		throw new Error('My helper function failed (on purpose)');
	}

})